# El formato SIEMPRE ES IMPORTANTE, sino no reconocera la configuracion
server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  datasource:
    url: jdbc:mysql://db:3307/db_learn_words?serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true&useSSL=false
#    url: jdbc:mysql://localhost/db_learn_words?serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=FALSE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      generate-ddl: true
#      show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
